/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DeepPDFPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/views/sidebar-view.ts
var import_obsidian2 = require("obsidian");

// src/ui/index-manager-modal.ts
var import_obsidian = require("obsidian");
var IndexManagerModal = class extends import_obsidian.Modal {
  constructor(app, apiClient) {
    super(app);
    this.apiClient = apiClient;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "PDF \u7D22\u5F15\u7BA1\u7406" });
    contentEl.createEl("p", {
      text: "\u7BA1\u7406 PDF \u7D22\u5F15\uFF0C\u7528\u4E8E\u6DF1\u5EA6\u67E5\u8BE2",
      cls: "deemphasized"
    });
    const buttonContainer = contentEl.createDiv({ cls: "index-button-container" });
    const importBtn = buttonContainer.createEl("button", {
      text: "+ \u5BFC\u5165 PDF",
      cls: "mod-cta"
    });
    importBtn.addEventListener("click", () => this.importPDF());
    const refreshBtn = buttonContainer.createEl("button", {
      text: "\u5237\u65B0\u7D22\u5F15\u5217\u8868"
    });
    refreshBtn.addEventListener("click", () => this.loadIndexes());
    contentEl.createDiv({ cls: "index-list" });
    await this.loadIndexes();
  }
  async loadIndexes() {
    const listContainer = this.contentEl.querySelector(".index-list");
    if (!listContainer)
      return;
    listContainer.empty();
    listContainer.createEl("p", { text: "\u52A0\u8F7D\u4E2D..." });
    try {
      const result = await this.apiClient.listIndexes();
      listContainer.empty();
      if (!result || !Array.isArray(result.indexes) || result.indexes.length === 0) {
        listContainer.createEl("p", {
          text: "\u6682\u65E0\u7D22\u5F15",
          cls: "deemphasized"
        });
        listContainer.createEl("p", {
          text: '\u63D0\u793A\uFF1A\u70B9\u51FB\u4E0A\u65B9 "\u5BFC\u5165 PDF" \u6309\u94AE\u5F00\u59CB\u521B\u5EFA\u7D22\u5F15',
          cls: "deemphasized"
        });
        return;
      }
      const tableWrapper = listContainer.createDiv({ cls: "index-table-wrapper" });
      const table = tableWrapper.createEl("table", {
        cls: "index-table"
      });
      const thead = table.createEl("thead");
      const headerRow = thead.createEl("tr");
      headerRow.createEl("th", { text: "PDF \u540D\u79F0" });
      headerRow.createEl("th", { text: "\u8282\u70B9\u6570" });
      headerRow.createEl("th", { text: "\u521B\u5EFA\u65F6\u95F4" });
      headerRow.createEl("th", { text: "\u64CD\u4F5C" });
      const tbody = table.createEl("tbody");
      result.indexes.forEach((index) => {
        const row = tbody.createEl("tr");
        row.createEl("td", {
          text: index.pdf_name,
          cls: "index-name"
        });
        row.createEl("td", {
          text: index.node_count.toString(),
          cls: "index-count"
        });
        row.createEl("td", {
          text: new Date(index.created_at).toLocaleString("zh-CN"),
          cls: "index-date"
        });
        const actionsCell = row.createEl("td", {
          cls: "index-actions"
        });
        const deleteBtn = actionsCell.createEl("button", {
          text: "\u5220\u9664",
          cls: "mod-warning"
        });
        deleteBtn.addEventListener("click", async () => {
          if (confirm(`\u786E\u5B9A\u8981\u5220\u9664\u7D22\u5F15 "${index.pdf_name}" \u5417\uFF1F`)) {
            await this.deleteIndex(index.id);
          }
        });
      });
    } catch (error) {
      listContainer.empty();
      listContainer.createEl("p", {
        text: `\u52A0\u8F7D\u7D22\u5F15\u5931\u8D25: ${error}`,
        cls: "deeppdf-error"
      });
    }
  }
  async deleteIndex(indexId) {
    try {
      const result = await this.apiClient.deleteIndex(indexId);
      if (result && result.status === "success") {
        new import_obsidian.Notice("\u7D22\u5F15\u5220\u9664\u6210\u529F");
        await this.loadIndexes();
      } else {
        new import_obsidian.Notice(`\u5220\u9664\u5931\u8D25: ${(result == null ? void 0 : result.message) || "\u672A\u77E5\u9519\u8BEF"}`);
      }
    } catch (error) {
      new import_obsidian.Notice(`\u5220\u9664\u5931\u8D25: ${error}`);
    }
  }
  /**
   * 导入 PDF 并创建索引
   */
  async importPDF() {
    new ImportPDFModal(this.app, this.apiClient).open();
  }
};
var ImportPDFModal = class extends import_obsidian.Modal {
  constructor(app, apiClient) {
    super(app);
    this.inputEl = null;
    this.submitBtn = null;
    this.apiClient = apiClient;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u5BFC\u5165 PDF \u7D22\u5F15" });
    const inputContainer = contentEl.createDiv({ cls: "import-input-container" });
    inputContainer.createEl("label", { text: "PDF \u6587\u4EF6\u8DEF\u5F84:" });
    this.inputEl = inputContainer.createEl("input", {
      type: "text",
      placeholder: "/path/to/your/file.pdf",
      cls: "import-file-input"
    });
    const hintEl = contentEl.createEl("p", {
      text: "\u63D0\u793A\uFF1A\u8F93\u5165 PDF \u6587\u4EF6\u7684\u5B8C\u6574\u8DEF\u5F84\uFF0C\u4F8B\u5982 /Users/xxx/Documents/paper.pdf",
      cls: "deemphasized"
    });
    const buttonContainer = contentEl.createDiv({ cls: "import-button-container" });
    const cancelBtn = buttonContainer.createEl("button", {
      text: "\u53D6\u6D88"
    });
    cancelBtn.addEventListener("click", () => this.close());
    this.submitBtn = buttonContainer.createEl("button", {
      text: "\u5F00\u59CB\u7D22\u5F15",
      cls: "mod-cta"
    });
    this.submitBtn.addEventListener("click", () => this.handleImport());
    this.inputEl.addEventListener("keypress", (e) => {
      if (e.key === "Enter" && this.submitBtn) {
        this.handleImport();
      }
    });
    setTimeout(() => {
      var _a;
      return (_a = this.inputEl) == null ? void 0 : _a.focus();
    }, 100);
  }
  async handleImport() {
    var _a, _b;
    const pdfPath = (_b = (_a = this.inputEl) == null ? void 0 : _a.value) == null ? void 0 : _b.trim();
    if (!pdfPath) {
      new import_obsidian.Notice("\u8BF7\u8F93\u5165 PDF \u6587\u4EF6\u8DEF\u5F84");
      return;
    }
    if (this.submitBtn) {
      this.submitBtn.disabled = true;
      this.submitBtn.textContent = "\u7D22\u5F15\u4E2D...";
    }
    const progressNotice = new import_obsidian.Notice(`\u6B63\u5728\u7D22\u5F15: ${pdfPath}`, 0);
    try {
      const result = await this.apiClient.indexPDF(pdfPath);
      progressNotice.hide();
      if (result && result.status === "success") {
        new import_obsidian.Notice(
          `\u7D22\u5F15\u521B\u5EFA\u6210\u529F\uFF01
PDF: ${result.pdf_name}
\u8282\u70B9\u6570: ${result.node_count}
\u7D22\u5F15 ID: ${result.index_id}`
        );
        this.close();
      } else if (result && result.status === "error") {
        new import_obsidian.Notice(`\u7D22\u5F15\u5931\u8D25: ${result.error || "\u672A\u77E5\u9519\u8BEF"}`);
        if (this.submitBtn) {
          this.submitBtn.disabled = false;
          this.submitBtn.textContent = "\u5F00\u59CB\u7D22\u5F15";
        }
      } else {
        new import_obsidian.Notice(`\u7D22\u5F15\u5931\u8D25: \u672A\u77E5\u9519\u8BEF`);
        if (this.submitBtn) {
          this.submitBtn.disabled = false;
          this.submitBtn.textContent = "\u5F00\u59CB\u7D22\u5F15";
        }
      }
    } catch (indexError) {
      progressNotice.hide();
      new import_obsidian.Notice(`\u7D22\u5F15\u5931\u8D25: ${indexError}`);
      if (this.submitBtn) {
        this.submitBtn.disabled = false;
        this.submitBtn.textContent = "\u5F00\u59CB\u7D22\u5F15";
      }
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/views/sidebar-view.ts
var SIDEBAR_VIEW_TYPE = "deeppdf-sidebar-view";
var SidebarView = class extends import_obsidian2.ItemView {
  constructor(leaf, apiClient) {
    super(leaf);
    this.apiClient = apiClient;
    this.submitHandler = () => {
    };
    this.keyPressHandler = () => {
    };
    this.indexSelectHandler = () => {
    };
  }
  getViewType() {
    return SIDEBAR_VIEW_TYPE;
  }
  getDisplayText() {
    return "DeepPDF";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("deeppdf-container");
    const header = container.createEl("header", { cls: "deeppdf-header" });
    header.createEl("h2", { text: "DeepPDF" });
    const statusEl = header.createEl("div", { cls: "deeppdf-status" });
    this.updateStatus(statusEl);
    const manageBtn = header.createEl("button", {
      cls: "deeppdf-manage-btn",
      text: "\u7BA1\u7406\u7D22\u5F15"
    });
    manageBtn.addEventListener("click", () => {
      this.openIndexManager();
    });
    const querySection = container.createEl("div", { cls: "deeppdf-query-section" });
    const indexSelectRow = querySection.createDiv({ cls: "deeppdf-index-select-row" });
    indexSelectRow.createEl("label", {
      text: "\u9009\u62E9\u7D22\u5F15:",
      cls: "deeppdf-index-label"
    });
    const indexSelect = indexSelectRow.createEl("select", {
      cls: "deeppdf-index-select"
    });
    indexSelect.add(new Option("\u52A0\u8F7D\u4E2D...", ""));
    const input = querySection.createEl("input", {
      type: "text",
      cls: "deeppdf-query-input",
      placeholder: "\u8F93\u5165\u95EE\u9898..."
    });
    const submitBtn = querySection.createEl("button", {
      cls: "deeppdf-submit-btn",
      text: "\u63D0\u95EE"
    });
    const resultsSection = container.createEl("div", { cls: "deeppdf-results-section" });
    resultsSection.createEl("p", {
      text: "\u8F93\u5165\u95EE\u9898\u5F00\u59CB\u67E5\u8BE2",
      cls: "deeppdf-placeholder"
    });
    this.submitHandler = () => this.handleSubmit(input.value, indexSelect.value);
    this.keyPressHandler = (e) => {
      if (e.key === "Enter") {
        this.handleSubmit(input.value, indexSelect.value);
      }
    };
    this.indexSelectHandler = () => {
      console.log(`[DeepPDF] \u9009\u4E2D\u7684\u7D22\u5F15: ${indexSelect.value}`);
    };
    submitBtn.addEventListener("click", this.submitHandler);
    input.addEventListener("keypress", this.keyPressHandler);
    indexSelect.addEventListener("change", this.indexSelectHandler);
    await this.loadIndexes(indexSelect);
  }
  async updateStatus(statusEl) {
    statusEl.empty();
    if (!this.apiClient) {
      statusEl.createEl("span", {
        text: "\u26A0\uFE0F API \u5BA2\u6237\u7AEF\u672A\u8FDE\u63A5",
        cls: "deeppdf-status-warning"
      });
    } else {
      const isHealthy = await this.apiClient.healthCheck();
      if (isHealthy) {
        statusEl.createEl("span", {
          text: "\u2705 API \u670D\u52A1\u5668\u5DF2\u8FDE\u63A5",
          cls: "deeppdf-status-ok"
        });
      } else {
        statusEl.createEl("span", {
          text: "\u26A0\uFE0F API \u670D\u52A1\u5668\u672A\u8FDE\u63A5",
          cls: "deeppdf-status-warning"
        });
      }
    }
  }
  openIndexManager() {
    if (!this.apiClient) {
      this.showError("API \u5BA2\u6237\u7AEF\u672A\u8FDE\u63A5");
      return;
    }
    new IndexManagerModal(this.app, this.apiClient).open();
  }
  async handleSubmit(query, selectedIndexId) {
    if (!query.trim()) {
      return;
    }
    if (!this.apiClient) {
      this.showError("API \u5BA2\u6237\u7AEF\u672A\u8FDE\u63A5");
      return;
    }
    const resultsSection = this.containerEl.querySelector(".deeppdf-results-section");
    if (!resultsSection)
      return;
    resultsSection.innerHTML = "<p>\u67E5\u8BE2\u4E2D...</p>";
    try {
      if (!selectedIndexId) {
        resultsSection.innerHTML = `
                    <div class="deeppdf-result">
                        <h3>\u67E5\u8BE2\u7ED3\u679C</h3>
                        <p class="deeppdf-notice">
                            \u26A0\uFE0F \u8BF7\u5148\u9009\u62E9\u4E00\u4E2A\u7D22\u5F15\u3002<br>
                            \u5982\u679C\u6CA1\u6709\u53EF\u7528\u7D22\u5F15\uFF0C\u8BF7\u4F7F\u7528"\u7BA1\u7406\u7D22\u5F15"\u521B\u5EFA PDF \u7D22\u5F15\u3002
                        </p>
                    </div>
                `;
        return;
      }
      const result = await this.apiClient.queryPDF(query, selectedIndexId);
      this.displayQueryResult(result, query, resultsSection);
    } catch (error) {
      resultsSection.innerHTML = `<p class="deeppdf-error">\u67E5\u8BE2\u5931\u8D25: ${error}</p>`;
    }
  }
  /**
   * 加载索引列表到选择器
   */
  async loadIndexes(indexSelect) {
    if (!this.apiClient) {
      indexSelect.innerHTML = '<option value="">\u672A\u8FDE\u63A5</option>';
      return;
    }
    try {
      const result = await this.apiClient.listIndexes();
      indexSelect.innerHTML = "";
      if (!result || !Array.isArray(result.indexes) || result.indexes.length === 0) {
        indexSelect.add(new Option("\u6682\u65E0\u7D22\u5F15", ""));
        return;
      }
      result.indexes.forEach((index) => {
        const option = new Option(
          `${index.pdf_name} (${index.node_count} \u8282\u70B9)`,
          index.id
        );
        indexSelect.add(option);
      });
      console.log(`[DeepPDF] \u5DF2\u52A0\u8F7D ${result.indexes.length} \u4E2A\u7D22\u5F15`);
    } catch (error) {
      console.error("[DeepPDF] \u52A0\u8F7D\u7D22\u5F15\u5217\u8868\u5931\u8D25:", error);
      indexSelect.innerHTML = '<option value="">\u52A0\u8F7D\u5931\u8D25</option>';
    }
  }
  displayQueryResult(result, query, resultsSection) {
    if (!result || result.status !== "success") {
      resultsSection.innerHTML = `
                <div class="deeppdf-result">
                    <h3>\u67E5\u8BE2\u7ED3\u679C</h3>
                    <p class="deeppdf-error">\u67E5\u8BE2\u5931\u8D25: ${"\u672A\u77E5\u9519\u8BEF"}</p>
                </div>
            `;
      return;
    }
    let resultsHtml = `
            <div class="deeppdf-result">
                <h3>\u67E5\u8BE2\u7ED3\u679C</h3>
                <p><strong>\u95EE\u9898:</strong> ${query}</p>
        `;
    if (result.results && Array.isArray(result.results) && result.results.length > 0) {
      resultsHtml += `<div class="deeppdf-results-list">`;
      result.results.forEach((item, index) => {
        var _a, _b, _c;
        const pageNumber = ((_a = item.metadata) == null ? void 0 : _a.page) || ((_b = item.metadata) == null ? void 0 : _b.start_index);
        resultsHtml += `
                    <div class="deeppdf-result-item">
                        <h4>\u7ED3\u679C ${index + 1}</h4>
                        <p class="deeppdf-result-text">${item.text || "\u65E0\u5185\u5BB9"}</p>
                        <div class="deeppdf-result-meta">
                            <span class="deeppdf-meta-label">\u7AE0\u8282:</span>
                            <span>${((_c = item.metadata) == null ? void 0 : _c.section) || "\u672A\u77E5"}</span>
                            <span class="deeppdf-meta-separator">\u2022</span>
                            <span class="deeppdf-meta-label">\u9875\u7801:</span>
                            <span>${pageNumber || "\u672A\u77E5"}</span>
                        </div>
                    </div>
                `;
      });
      resultsHtml += `</div>`;
    } else {
      resultsHtml += `<p class="deeppdf-notice">\u672A\u627E\u5230\u76F8\u5173\u7ED3\u679C</p>`;
    }
    resultsHtml += `</div>`;
    resultsSection.innerHTML = resultsHtml;
  }
  showError(message) {
    const resultsSection = this.containerEl.querySelector(".deeppdf-results-section");
    if (resultsSection) {
      resultsSection.innerHTML = `<p class="deeppdf-error">${message}</p>`;
    }
  }
  async onClose() {
    const submitBtn = this.containerEl.querySelector(".deeppdf-submit-btn");
    const input = this.containerEl.querySelector(".deeppdf-query-input");
    const indexSelect = this.containerEl.querySelector(".deeppdf-index-select");
    if (submitBtn) {
      submitBtn.removeEventListener("click", this.submitHandler);
    }
    if (input) {
      input.removeEventListener("keypress", this.keyPressHandler);
    }
    if (indexSelect) {
      indexSelect.removeEventListener("change", this.indexSelectHandler);
    }
  }
};

// src/api/http-client.ts
var DeepPDFClient = class {
  constructor(port) {
    this.DEFAULT_PORT = 8e3;
    this.baseUrl = `http://localhost:${port || this.DEFAULT_PORT}`;
  }
  /**
   * 健康检查
   */
  async healthCheck() {
    try {
      const response = await fetch(`${this.baseUrl}/health`);
      const data = await response.json();
      return data.status === "ok";
    } catch (e) {
      return false;
    }
  }
  /**
   * 创建 PDF 索引
   */
  async indexPDF(pdfPath) {
    const response = await fetch(`${this.baseUrl}/api/index`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ path: pdfPath })
    });
    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.detail || "Index creation failed");
    }
    return response.json();
  }
  /**
   * 查询 PDF
   */
  async queryPDF(query, indexId) {
    const response = await fetch(`${this.baseUrl}/api/query`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ query, index_id: indexId })
    });
    if (!response.ok) {
      throw new Error("Query failed");
    }
    return response.json();
  }
  /**
   * 列出所有索引
   */
  async listIndexes() {
    const response = await fetch(`${this.baseUrl}/api/indexes`);
    return response.json();
  }
  /**
   * 删除索引
   */
  async deleteIndex(indexId) {
    const response = await fetch(`${this.baseUrl}/api/indexes/${indexId}`, {
      method: "DELETE"
    });
    return response.json();
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  apiPort: 6088,
  maxResults: 5,
  deepseekApiKey: "",
  openaiApiKey: "",
  llmProvider: "deepseek",
  llmModel: "deepseek-chat",
  apiUrl: "",
  maxPagesPerNode: 10,
  maxTokensPerNode: 2e4,
  ifAddNodeSummary: true
};
var DeepPDFPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.apiClient = null;
  }
  async onload() {
    console.log("[DeepPDF] Loading plugin");
    await this.loadSettings();
    this.apiClient = new DeepPDFClient(this.settings.apiPort);
    const isHealthy = await this.apiClient.healthCheck();
    if (!isHealthy) {
      console.log("[DeepPDF] Server not running at localhost:" + this.settings.apiPort);
      new import_obsidian3.Notice(`DeepPDF: \u65E0\u6CD5\u8FDE\u63A5\u5230\u670D\u52A1\u5668 localhost:${this.settings.apiPort}\uFF0C\u8BF7\u786E\u4FDD\u540E\u7AEF\u5DF2\u542F\u52A8`);
    } else {
      console.log("[DeepPDF] Server connected successfully");
    }
    this.registerView(
      SIDEBAR_VIEW_TYPE,
      (leaf) => new SidebarView(leaf, this.apiClient)
    );
    this.addSettingTab(new DeepPDFSettingTab(this.app, this));
    this.addRibbonIcon("book", "DeepPDF", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-deeppdf-sidebar",
      name: "Open DeepPDF sidebar",
      callback: () => this.activateView()
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async onunload() {
  }
  activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(SIDEBAR_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (!leaf)
        return;
      leaf.setViewState({
        type: SIDEBAR_VIEW_TYPE,
        active: true
      });
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
};
var DeepPDFSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "API Server \u8BBE\u7F6E" });
    new import_obsidian3.Setting(containerEl).setName("API Port").setDesc("FastAPI \u670D\u52A1\u5668\u7AEF\u53E3\uFF08\u9ED8\u8BA4 localhost:6088\uFF09").addText((text) => text.setPlaceholder("6088").setValue(String(this.plugin.settings.apiPort)).onChange(async (value) => {
      this.plugin.settings.apiPort = parseInt(value) || 6088;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Max Results").setDesc("Maximum number of results to return").addSlider((slider) => slider.setLimits(1, 20, 1).setValue(this.plugin.settings.maxResults).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.maxResults = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h2", { text: "LLM API \u8BBE\u7F6E" });
    new import_obsidian3.Setting(containerEl).setName("LLM Provider").setDesc("Select LLM provider for PDF indexing").addDropdown((dropdown) => dropdown.addOption("deepseek", "DeepSeek").addOption("openai", "OpenAI").addOption("google", "Google").addOption("custom", "Custom").setValue(this.plugin.settings.llmProvider).onChange(async (value) => {
      this.plugin.settings.llmProvider = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("LLM Model").setDesc("Model name to use (e.g., deepseek-chat, gpt-4)").addText((text) => text.setPlaceholder("deepseek-chat").setValue(this.plugin.settings.llmModel).onChange(async (value) => {
      this.plugin.settings.llmModel = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("DeepSeek API Key").setDesc("DeepSeek API key for LLM indexing").addText((text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.deepseekApiKey).onChange(async (value) => {
      this.plugin.settings.deepseekApiKey = value;
      await this.plugin.saveSettings();
    })).then((setting) => {
      const inputEl = setting.controlEl.querySelector("input");
      if (inputEl)
        inputEl.type = "password";
    });
    new import_obsidian3.Setting(containerEl).setName("OpenAI API Key").setDesc("OpenAI API key (for OpenAI provider)").addText((text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.openaiApiKey).onChange(async (value) => {
      this.plugin.settings.openaiApiKey = value;
      await this.plugin.saveSettings();
    })).then((setting) => {
      const inputEl = setting.controlEl.querySelector("input");
      if (inputEl)
        inputEl.type = "password";
    });
    new import_obsidian3.Setting(containerEl).setName("API Base URL").setDesc("Custom API endpoint (optional, for custom provider)").addText((text) => text.setPlaceholder("https://api.example.com/v1").setValue(this.plugin.settings.apiUrl).onChange(async (value) => {
      this.plugin.settings.apiUrl = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h2", { text: "PDF \u7D22\u5F15\u8BBE\u7F6E" });
    new import_obsidian3.Setting(containerEl).setName("Max Pages Per Node").setDesc("Maximum pages per section node").addSlider((slider) => slider.setLimits(1, 50, 1).setValue(this.plugin.settings.maxPagesPerNode).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.maxPagesPerNode = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Max Tokens Per Node").setDesc("Maximum tokens per section node").addSlider((slider) => slider.setLimits(1e3, 5e4, 1e3).setValue(this.plugin.settings.maxTokensPerNode).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.maxTokensPerNode = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Add Node Summary").setDesc("Use LLM to generate section summaries").addToggle((toggle) => toggle.setValue(this.plugin.settings.ifAddNodeSummary).onChange(async (value) => {
      this.plugin.settings.ifAddNodeSummary = value;
      await this.plugin.saveSettings();
    }));
  }
};
