import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
        // Node.js built-in modules with node: prefix (used by vault features)
        "node:fs",
        "node:fs/promises",
        "node:path",
        "node:crypto",
        "node:os",
        "node:util",
        "node:stream",
        "node:events",
        // PageIndex dependencies - large libraries loaded at runtime
        "pdf-parse",
        "adm-zip",
        "xml2js",
        "turndown",
        // Bun-specific vault features (loaded dynamically at runtime)
        "./pageindex/vault/*",
        "./pageindex/parsers/pdf-to-markdown"],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
